<a href="https://colab.research.google.com/github/harishmuh/Python-for-Data-Science-Analysis/blob/main/Numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Exercise**
---

In [1]:
# Importing library
import numpy as np

### **Number 1**
Create a 1D array with the variable name Array consisting of 36 random integer numbers between 1 and 100! (Use seed=0)

In [2]:
np.random.seed(0)
myArray = np.random.randint(1, 101, 36)
myArray

array([ 45,  48,  65,  68,  68,  10,  84,  22,  37,  88,  71,  89,  89,
        13,  59,  66,  40,  88,  47,  89,  82,  38,  26,  78,  73,  10,
        21,  81,  70,  80,  48,  65,  83, 100,  89,  50])

### **Number 2**

Change the array (myArray) into

* a 2D array with size 2 x 18
* a 2D array with size 9 x 4
* a 3D array with size 2 x 6 X 3

In [3]:
myArray.reshape(2, 18)

array([[ 45,  48,  65,  68,  68,  10,  84,  22,  37,  88,  71,  89,  89,
         13,  59,  66,  40,  88],
       [ 47,  89,  82,  38,  26,  78,  73,  10,  21,  81,  70,  80,  48,
         65,  83, 100,  89,  50]])

In [4]:
myArray.reshape(9, 4)

array([[ 45,  48,  65,  68],
       [ 68,  10,  84,  22],
       [ 37,  88,  71,  89],
       [ 89,  13,  59,  66],
       [ 40,  88,  47,  89],
       [ 82,  38,  26,  78],
       [ 73,  10,  21,  81],
       [ 70,  80,  48,  65],
       [ 83, 100,  89,  50]])

In [5]:
myArray.reshape(2, 6, 3)

array([[[ 45,  48,  65],
        [ 68,  68,  10],
        [ 84,  22,  37],
        [ 88,  71,  89],
        [ 89,  13,  59],
        [ 66,  40,  88]],

       [[ 47,  89,  82],
        [ 38,  26,  78],
        [ 73,  10,  21],
        [ 81,  70,  80],
        [ 48,  65,  83],
        [100,  89,  50]]])

### **Number 3**

Determine

* the minimum value of the array (myArray)
* the maximum value of the array (myArray)
* the position of the minimum value
* the position of the maximum value

In [6]:
print(f'''Minimum value: {np.min(myArray)}
Maximum value: {np.max(myArray)}
Minimum position: {np.argmin(myArray)}
Maximum position: {np.argmax(myArray)}
''')

Minimum value: 10
Maximum value: 100
Minimum position: 5
Maximum position: 33



### **Number 4**

Create a new array with the variable name new_array containing 9 numbers taken from the 3rd, 5th, 30th, 12th, 15th, 8th, 24th, 14th, and 22nd data from myArray!

Change the array into a 2D array with a size of 3 x 3 permanently!

In [7]:
new_array = myArray[[3, 5, 30, 12, 15, 8, 24, 14,22]].reshape(3, 3)
new_array

array([[68, 10, 48],
       [89, 66, 37],
       [73, 59, 26]])

### **Number 5**

Show items in new_array whose value is greater than 50!

In [8]:
new_array[new_array > 50]

array([68, 89, 66, 73, 59])

### **Number 6**

Create a 1D array containing the numbers 0, 25, 50, 75, and 100 using the functions:

* arange
* linspace

In [9]:
np.arange(0,101,25)

array([  0,  25,  50,  75, 100])

In [10]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

### **Number 7**

Create a 2D array of size N X N that all contain the number 8, where n is a natural number whose size is requested for input to the user!

example :\
The inputted N is: 2

result :\
array([[8., 8.],\
&emsp;&emsp;&nbsp;&nbsp;&nbsp;[8., 8.]])

In [12]:
number = int(input('N inputted is: '))

np.ones((number,number)) * 8

N inputted is: 5


array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

### **Number 8**

Create a 2D array named arrayA measuring 3 x 4 with the following results:

In [13]:
arrayA = np.arange(1,13).reshape(3, 4)
arrayA

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Create a 2D array named arrayB measuring 4 x 1 with the following results:

In [14]:
arrayB = np.linspace(100, 400, 4).reshape(4, 1)
arrayB

array([[100.],
       [200.],
       [300.],
       [400.]])

Combine arrays and arrays into an array with the following results:

In [15]:
arrayC = np.concatenate((arrayA, arrayB.T), axis=0)
arrayC

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.],
       [100., 200., 300., 400.]])

### **Number 9**

Show the following results by slicing arrayC!

In [16]:
arrayC[1:3, 2:]

array([[ 7.,  8.],
       [11., 12.]])

### **Number 10**

Show the following results by slicing arrayC!

In [17]:
arrayC[3, 1]

np.float64(200.0)

### **Number 11**

Convert the data set below into a numpy array!

In [18]:
arr = [[1,2,3],[4,5,6],[7,8,9]]
arr_2 = ((10,11,12),(13,14,15),(16,17,8))

In [19]:
print(np.array(arr))
print(np.array(arr_2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17  8]]


In [20]:
print(f'arr : {type(arr)}, arr_np : {type(np.array(arr))}')
print(f'arr_2 : {type(arr_2)}, arr_np_2 : {type(np.array(arr_2))}')

arr : <class 'list'>, arr_np : <class 'numpy.ndarray'>
arr_2 : <class 'tuple'>, arr_np_2 : <class 'numpy.ndarray'>


### **Number 12**

Create a numpy array like the example below!

In [21]:
np.arange(1,26).reshape(5, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### **Number 13**

Create a numpy array like the example below!

In [22]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [23]:
np.linspace(1,19,10)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [24]:
array = np.arange(1,20)
array[array % 2 != 0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

### **Number 14**

Create a random numpy array of numbers 1-10 as many as 20 and arrange them as in the example below (Use seed=32)!

In [25]:
np.random.seed(32)
np.random.randint(1,11,20).reshape(5, 4)

array([[ 8,  6,  7,  9],
       [ 4,  8, 10,  4],
       [ 6, 10,  5,  2],
       [ 4,  2,  3,  4],
       [ 9,  3,  5,  3]])

### **Number 15**

Create a random numpy array of numbers 0-1 of 10 numbers as in the example below (Use seed=101)

In [26]:
np.random.seed(101)
np.random.rand(10)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166, 0.68527698,
       0.83389686, 0.30696622, 0.89361308, 0.72154386, 0.18993895])

### **Number 16**

Create a 2D array as follows and save it into a variable named 'matrix'.

In [27]:
matrix = np.arange(1, 26).reshape(5, 5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### **Number 17**

Perform indexing of the matrix variables to get the example below!

In [28]:
matrix[4, :3]

array([21, 22, 23])

### **Number 18**

Perform indexing of the matrix variables to get the example below!

In [29]:
matrix[:, -1]

array([ 5, 10, 15, 20, 25])

### **Number 19**

Perform indexing of the matrix variables to get the example below!

In [30]:
matrix[1:4, 1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

### **Number 20**

Perform indexing of the matrix variables to get the example below!

In [31]:
matrix[1:, 3:]

array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

### **Number 21**
Display some information from the array variable that has been created as in the example below!

In [32]:
np.random.seed(101)
arr = np.random.randint(1,10,20)
arr

array([2, 7, 8, 9, 5, 9, 6, 1, 6, 9, 2, 4, 9, 4, 4, 3, 9, 4, 8, 1])

In [33]:
print(f'''Mean : {np.mean(arr)}
Median : {np.median(arr)}
Max : {np.max(arr)}
Min : {np.min(arr)}
Max Index : {np.argmax(arr)}
Min Index: {np.argmin(arr)}
Shape: {np.shape(arr)}
''')

Mean : 5.5
Median : 5.5
Max : 9
Min : 1
Max Index : 3
Min Index: 7
Shape: (20,)



### **Number 22**

Try to combine array_a and array_b like the example below!

In [34]:
array_a = np.array([[1, 2], [3, 4]])
array_b = np.array([[5, 6, 7], [8, 9, 10]])

In [35]:
np.concatenate((array_a, array_b), axis=1)

array([[ 1,  2,  5,  6,  7],
       [ 3,  4,  8,  9, 10]])

### **Number 23**

Change the arr variable below to be like the example below!

In [36]:
arr = np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr * arr

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [38]:
arr ** 2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

### **Number 24**

Change the array_x variable below to be like the example below!

In [39]:
x = np.arange(1,21).reshape(5,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [40]:
x + np.array([0, 1, 2, 3])

array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13, 15, 17, 19],
       [17, 19, 21, 23]])

### **Number 25**

Create a 2D array measuring 8 X 8 that has a chessboard pattern according to the following example:

In [41]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2]=1
checkerboard[::2, 1::2]=1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
